version: '2.4'

services:
  router:
    image: ayudadigital/gp-haproxy:2.0.0
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/router/usr/local/etc/haproxy:/usr/local/etc/haproxy
      - ./data/router/etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    depends_on:
      app:
        condition: service_healthy
  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: ${DATASOURCE_DBNAME}
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
    volumes:
      - ./data/db/var/lib/postgresql/data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname ${DATASOURCE_DBNAME} --username ${DATASOURCE_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    image: ayudadigital/huelladigital:${tag_app}
    environment:
      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_DBNAME: ${DATASOURCE_DBNAME}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      PROFILE: ${PROFILE}
      BASE_URI: ${BASE_URI}
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - localhost:8080/actuator/health 2>&1 | grep UP || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
